export const UPDATE_APPLICATION_REQUEST = 'UPDATE_APPLICATION_REQUEST';
export const UPDATE_APPLICATION_SUCCESS = 'UPDATE_APPLICATION_SUCCESS';
export const UPDATE_APPLICATION_FAILURE = 'UPDATE_APPLICATION_FAILURE';

export const UPLOAD_APPLICATION_PACKAGE_REQUEST = 'UPLOAD_APPLICATION_PACKAGE_REQUEST';
export const UPLOAD_APPLICATION_PACKAGE_SUCCESS = 'UPLOAD_APPLICATION_PACKAGE_SUCCESS';
export const UPLOAD_APPLICATION_PACKAGE_FAILURE = 'UPLOAD_APPLICATION_PACKAGE_FAILURE';

export const START_APPLICATION_REQUEST = 'START_APPLICATION_REQUEST';
export const START_APPLICATION_SUCCESS = 'START_APPLICATION_SUCCESS';
export const START_APPLICATION_FAILURE = 'START_APPLICATION_FAILURE';

export const PAUSE_APPLICATION_REQUEST = 'PAUSE_APPLICATION_REQUEST';
export const PAUSE_APPLICATION_SUCCESS = 'PAUSE_APPLICATION_SUCCESS';
export const PAUSE_APPLICATION_FAILURE = 'PAUSE_APPLICATION_FAILURE';

export const RESTART_APPLICATION_REQUEST = 'RESTART_APPLICATION_REQUEST';
export const RESTART_APPLICATION_SUCCESS = 'RESTART_APPLICATION_SUCCESS';
export const RESTART_APPLICATION_FAILURE = 'RESTART_APPLICATION_FAILURE';

export const STOP_APPLICATION_REQUEST = 'STOP_APPLICATION_REQUEST';
export const STOP_APPLICATION_SUCCESS = 'STOP_APPLICATION_SUCCESS';
export const STOP_APPLICATION_FAILURE = 'STOP_APPLICATION_FAILURE';

export const RELOAD_APPLICATION_REQUEST = 'RELOAD_APPLICATION_REQUEST';
export const RELOAD_APPLICATION_SUCCESS = 'RELOAD_APPLICATION_SUCCESS';
export const RELOAD_APPLICATION_FAILURE = 'RELOAD_APPLICATION_FAILURE';

export const CHECK_APPLICATION_NAME_EXIST_REQUEST = 'CHECK_APPLICATION_NAME_EXIST_REQUEST';
export const CHECK_APPLICATION_NAME_EXIST_SUCCESS = 'CHECK_APPLICATION_NAME_EXIST_SUCCESS';
export const CHECK_APPLICATION_NAME_EXIST_FAILURE = 'CHECK_APPLICATION_NAME_EXIST_FAILURE';

export const RENAME_APPLICATION_REQUEST = 'RENAME_APPLICATION_REQUEST';
export const RENAME_APPLICATION_SUCCESS = 'RENAME_APPLICATION_SUCCESS';
export const RENAME_APPLICATION_FAILURE = 'RENAME_APPLICATION_FAILURE';
