export const SHOW_CREATE_APPLICATION = 'SHOW_CREATE_APPLICATION';
export const HIDE_CREATE_APPLICATION = 'HIDE_CREATE_APPLICATION';

export const INIT_CREATE_APPLICATION_FORM = 'INIT_CREATE_APPLICATION_FORM';
export const UPDATE_CREATE_APPLICATION_FIELD = 'UPDATE_CREATE_APPLICATION_FIELD';
export const VALID_CREATE_APPLICATION_FORM = 'VALID_CREATE_APPLICATION_FORM';

export const CREATE_APPLICATION_REQUEST = 'CREATE_APPLICATION_REQUEST';
export const CREATE_APPLICATION_SUCCESS = 'CREATE_APPLICATION_SUCCESS';
export const CREATE_APPLICATION_FAILURE = 'CREATE_APPLICATION_FAILURE';
