export const CREATE_APPLICATION_REQUEST = 'CREATE_APPLICATION_REQUEST';
export const CREATE_APPLICATION_SUCCESS = 'CREATE_APPLICATION_SUCCESS';
export const CREATE_APPLICATION_FAILURE = 'CREATE_APPLICATION_FAILURE';

export const START_APPLICATION_REQUEST = 'START_APPLICATION_REQUEST';
export const START_APPLICATION_SUCCESS = 'START_APPLICATION_SUCCESS';
export const START_APPLICATION_FAILURE = 'START_APPLICATION_FAILURE';

export const PAUSE_APPLICATION_REQUEST = 'PAUSE_APPLICATION_REQUEST';
export const PAUSE_APPLICATION_SUCCESS = 'PAUSE_APPLICATION_SUCCESS';
export const PAUSE_APPLICATION_FAILURE = 'PAUSE_APPLICATION_FAILURE';

export const RESTART_APPLICATION_REQUEST = 'RESTART_APPLICATION_REQUEST';
export const RESTART_APPLICATION_SUCCESS = 'RESTART_APPLICATION_SUCCESS';
export const RESTART_APPLICATION_FAILURE = 'RESTART_APPLICATION_FAILURE';

export const STOP_APPLICATION_REQUEST = 'STOP_APPLICATION_REQUEST';
export const STOP_APPLICATION_SUCCESS = 'STOP_APPLICATION_SUCCESS';
export const STOP_APPLICATION_FAILURE = 'STOP_APPLICATION_FAILURE';

export const RELOAD_APPLICATION_REQUEST = 'RELOAD_APPLICATION_REQUEST';
export const RELOAD_APPLICATION_SUCCESS = 'RELOAD_APPLICATION_SUCCESS';
export const RELOAD_APPLICATION_FAILURE = 'RELOAD_APPLICATION_FAILURE';
