export const START_PROCESS_REQUEST = 'START_PROCESS_REQUEST';
export const START_PROCESS_SUCCESS = 'START_PROCESS_SUCCESS';
export const START_PROCESS_FAILURE = 'START_PROCESS_FAILURE';

export const PAUSE_PROCESS_REQUEST = 'PAUSE_PROCESS_REQUEST';
export const PAUSE_PROCESS_SUCCESS = 'PAUSE_PROCESS_SUCCESS';
export const PAUSE_PROCESS_FAILURE = 'PAUSE_PROCESS_FAILURE';

export const RESTART_PROCESS_REQUEST = 'RESTART_PROCESS_REQUEST';
export const RESTART_PROCESS_SUCCESS = 'RESTART_PROCESS_SUCCESS';
export const RESTART_PROCESS_FAILURE = 'RESTART_PROCESS_FAILURE';

export const STOP_PROCESS_REQUEST = 'STOP_PROCESS_REQUEST';
export const STOP_PROCESS_SUCCESS = 'STOP_PROCESS_SUCCESS';
export const STOP_PROCESS_FAILURE = 'STOP_PROCESS_FAILURE';

export const RELOAD_PROCESS_REQUEST = 'RELOAD_PROCESS_REQUEST';
export const RELOAD_PROCESS_SUCCESS = 'RELOAD_PROCESS_SUCCESS';
export const RELOAD_PROCESS_FAILURE = 'RELOAD_PROCESS_FAILURE';
