export const UPLOAD_PROCESS_PACKAGE_REQUEST = 'UPLOAD_PROCESS_PACKAGE_REQUEST';
export const UPLOAD_PROCESS_PACKAGE_SUCCESS = 'UPLOAD_PROCESS_PACKAGE_SUCCESS';
export const UPLOAD_PROCESS_PACKAGE_FAILURE = 'UPLOAD_PROCESS_PACKAGE_FAILURE';