export const ADD_SUCCESS_TOAST_ASYNC = 'ADD_SUCCESS_TOAST_ASYNC';
export const ADD_ERROR_TOAST_ASYNC = 'ADD_ERROR_TOAST_ASYNC';
export const ADD_INFO_NOTIFICATION_ASYNC = 'ADD_INFO_NOTIFICATION_ASYNC';
export const ADD_WARNING_NOTIFICATION_ASYNC = 'ADD_WARNING_NOTIFICATION_ASYNC';

export const CLEAR_ASYNC_MSG_SEQ = 'CLEAR_ASYNC_MSG_SEQ';