export const UPDATE_ROUTE_PARAM_REPORT = 'UPDATE_ROUTE_PARAM_REPORT';
export const UPDATE_ROUTE_PARAM_CAMPAIGN = 'UPDATE_ROUTE_PARAM_CAMPAIGN';
export const UPDATE_ROUTE_PARAM_CAMPAIGN_GROUP = 'UPDATE_ROUTE_PARAM_CAMPAIGN_GROUP';
export const UPDATE_ROUTE_PARAM_CAMPAIGN_HOTEL = 'UPDATE_ROUTE_PARAM_CAMPAIGN_HOTEL';
export const UPDATE_ROUTE_PARAM_CAMPAIGN_STRATEGY = 'UPDATE_ROUTE_PARAM_CAMPAIGN_STRATEGY';