export const GET_PATIENTS_REQUEST = 'GET_PATIENTS_REQUEST';
export const GET_PATIENTS_SUCCESS = 'GET_PATIENTS_SUCCESS';
export const GET_PATIENTS_FAILURE = 'GET_PATIENTS_FAILURE';

export const GET_FULL_PATIENTS_REQUEST = 'GET_FULL_PATIENTS_REQUEST';
export const GET_FULL_PATIENTS_SUCCESS = 'GET_FULL_PATIENTS_SUCCESS';
export const GET_FULL_PATIENTS_FAILURE = 'GET_FULL_PATIENTS_FAILURE';

export const UPDATE_PATIENT_NAME_REQUEST = 'UPDATE_PATIENT_NAME_REQUEST';
export const UPDATE_PATIENT_NAME_SUCCESS = 'UPDATE_PATIENT_NAME_SUCCESS';
export const UPDATE_PATIENT_NAME_FAILURE = 'UPDATE_PATIENT_NAME_FAILURE';

export const UPDATE_PATIENT_GROUP_REQUEST = 'UPDATE_PATIENT_GROUP_REQUEST';
export const UPDATE_PATIENT_GROUP_SUCCESS = 'UPDATE_PATIENT_GROUP_SUCCESS';
export const UPDATE_PATIENT_GROUP_FAILURE = 'UPDATE_PATIENT_GROUP_FAILURE';

export const ENABLE_PATIENT_REQUEST = 'ENABLE_PATIENT_REQUEST';
export const ENABLE_PATIENT_SUCCESS = 'ENABLE_PATIENT_SUCCESS';
export const ENABLE_PATIENT_FAILURE = 'ENABLE_PATIENT_FAILURE';

export const DISABLE_PATIENT_REQUEST = 'DISABLE_PATIENT_REQUEST';
export const DISABLE_PATIENT_SUCCESS = 'DISABLE_PATIENT_SUCCESS';
export const DISABLE_PATIENT_FAILURE = 'DISABLE_PATIENT_FAILURE';