export const GET_SENSORY_BLOCKS_REQUEST = 'GET_SENSORY_BLOCKS_REQUEST';
export const GET_SENSORY_BLOCKS_SUCCESS = 'GET_SENSORY_BLOCKS_SUCCESS';
export const GET_SENSORY_BLOCKS_FAILURE = 'GET_SENSORY_BLOCKS_FAILURE';