export const APPEND_TIME_POINT = 'APPEND_TIME_POINT';

export const UPDATE_ANALGESIA_FIELD = 'UPDATE_ANALGESIA_FIELD';

export const GET_ANALGESIA_REQUEST = 'GET_ANALGESIA_REQUEST';
export const GET_ANALGESIA_SUCCESS = 'GET_ANALGESIA_SUCCESS';
export const GET_ANALGESIA_FAILURE = 'GET_ANALGESIA_FAILURE';

export const UPDATE_ANALGESIA_REQUEST = 'UPDATE_ANALGESIA_REQUEST';
export const UPDATE_ANALGESIA_SUCCESS = 'UPDATE_ANALGESIA_SUCCESS';
export const UPDATE_ANALGESIA_FAILURE = 'UPDATE_ANALGESIA_FAILURE';