export const PATIENT_STEP_PREV = 'PATIENT_STEP_PREV';
export const PATIENT_STEP_NEXT = 'PATIENT_STEP_NEXT';
export const PATIENT_STEP_UPDATE = 'PATIENT_STEP_UPDATE';

export const RESET_PATIENT_DATA = 'RESET_PATIENT_DATA';