export const RESET_PATIENT_BASE_INFO = 'RESET_PATIENT_BASE_INFO';

export const UPDATE_PATIENT_BASE_INFO_FIELD = 'UPDATE_PATIENT_BASE_INFO_FIELD';

export const CREATE_PATIENT_REQUEST = 'GET_PATIENT_INFO_REQUEST';
export const CREATE_PATIENT_SUCCESS = 'GET_PATIENT_INFO_SUCCESS';
export const CREATE_PATIENT_FAILURE = 'GET_PATIENT_INFO_FAILURE';