export const UPDATE_PATIENT_INFO_FIELD = 'UPDATE_PATIENT_INFO_FIELD';

export const GET_PATIENT_INFO_REQUEST = 'GET_PATIENT_INFO_REQUEST';
export const GET_PATIENT_INFO_SUCCESS = 'GET_PATIENT_INFO_SUCCESS';
export const GET_PATIENT_INFO_FAILURE = 'GET_PATIENT_INFO_FAILURE';

export const UPDATE_PATIENT_INFO_REQUEST = 'UPDATE_PATIENT_INFO_REQUEST';
export const UPDATE_PATIENT_INFO_SUCCESS = 'UPDATE_PATIENT_INFO_SUCCESS';
export const UPDATE_PATIENT_INFO_FAILURE = 'UPDATE_PATIENT_INFO_FAILURE';